"""add color and size to products

Revision ID: 67a1a6f1290e
Revises: 0450867a89fe
Create Date: 2026-07-22 12:51:09.237662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67a1a6f1290e'
down_revision: Union[str, Sequence[str], None] = '0450867a89fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('color', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('size', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'size')
    op.drop_column('products', 'color')
    # ### end Alembic commands ###
